// <auto-generated />
using System;
using DarlingBotNet.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DarlingBotNet.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20200712194502_marryedadd")]
    partial class marryedadd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("DarlingBotNet.DataBase.Channels", b =>
                {
                    b.Property<ulong>("channelid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadWordString")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GiveXP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InviteMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendBadWord")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendCaps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendUrl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Spaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommand")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("antiMat")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guildid")
                        .HasColumnType("INTEGER");

                    b.HasKey("channelid");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.EmoteClick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("channelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("emote")
                        .HasColumnType("TEXT");

                    b.Property<bool>("get")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guildid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("messageid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("roleid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmoteClick");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.Guilds", b =>
                {
                    b.Property<ulong>("guildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandInviseString")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GiveXPnextChannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LeaveChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leaved")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MafiaWaitChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PrivateChannelID")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ViolationSystem")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("WelcomeChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WelcomeDMmessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WelcomeDMuser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("WelcomeRole")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("banchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("chatmuterole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("inviteMessages")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("joinchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("kickchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("leftchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("mesdelchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("meseditchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("unbanchannel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("voiceUserActions")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("voicemuterole")
                        .HasColumnType("INTEGER");

                    b.HasKey("guildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.LVLROLES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("countlvl")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guildid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("roleid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LVLROLES");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.PrivateChannels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("channelid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guildid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrivateChannels");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.TempUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("guildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TempUser");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.UserRules", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RulesNumber")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RulesPoint")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserRules");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.Users", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Daily")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leaved")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("XP")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ZeroCoin")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("countwarns")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("marryedid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DarlingBotNet.DataBase.Warns", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CountWarn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportWarn")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("guildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Warns");
                });
#pragma warning restore 612, 618
        }
    }
}
